language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t markiyan96/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true markiyan96/docker-react npm run test
